const colors = {
  charcoal: '#414141',
  white: '#ffffff',
  black: '#000000',
  blue: '#2258F5',
  navy: '#0C315B',
  dark: '#333333',
  superLightBlue: '#F4FAFF',
  lightBlue: '#F5FAFF',
  lightNavy: '#E6EDF6',
  lightGrey: '#F0F0F0',
  gray: '#DADADA',
  gray20: '#F5F5F5',
  gray30: '#E8E8E8',
  gray40: '#E2E8F0',
  gray50: '#BCBCBC',
  gray60: '#BABABA',
  gray70: '#737373',
  gray80: '#5B5B5B',
  green: '#1F6F00',
  red400: '#f56565',
  red500: '#e53e3e',
  lightGreen: '#56C12C',
  lightBlack: '#333333',
  transparent01: 'rgba(0, 0, 0, 0.1)',
  aqua: '4AEFDF',
}

export default {
  main: {
    background: colors.blue,
    white: colors.white,
    green: colors.green,
    blue: colors.blue,
    lightGreen: colors.lightGreen,
    grey: colors.gray,
    lightGrey: colors.lightGrey,
    dark: colors.dark,
    lightNavy: colors.lightNavy,
    mediumGrey: colors.gray60,
    darkGrey: colors.gray70,
    navy: colors.navy,
    red: colors.red400,
    darkRed: colors.red500,
    lightBlue: colors.lightBlue,
    lightBlack: colors.lightBlack,
    '01': colors.transparent01,
    charcoal: colors.charcoal,
    aque: colors.aqua,
  },
  section: {
    title: colors.gray80,
  },

  text: {
    black: colors.black,
    white: colors.white,
    gray50: colors.gray50,
  },
}
